{% set name = "proxyspy" %}
{% set version = "0.1.4" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 87f1e3fa0c26c750ba8488448df71b8b2d36c514414075a955f0956ad603a4af

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - proxyspy = proxyspy:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - cryptography

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - proxyspy
  commands:
    - pip check
    - proxyspy --help

about:
  home: https://github.com/anaconda/proxyspy
  summary: A debugging proxy that can log or intercept HTTPS requests
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    A debugging proxy that can log or intercept HTTPS requests. This tool can be used to:
    - Monitor HTTPS traffic from applications
    - Debug SSL/TLS issues
    - Test applications against specific HTTP responses
    - Simulate network delays
  doc_url: https://github.com/anaconda/proxyspy
  dev_url: https://github.com/anaconda/proxyspy

extra:
  recipe-maintainers:
    - mcg1969
    - jezdez
